{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.cloudmc",
    "module": "cloudscript-module-gradle-plugin",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cloudscript-module-gradle-plugin-0.4.6.jar",
          "url": "cloudscript-module-gradle-plugin-0.4.6.jar",
          "size": 712844,
          "sha512": "766f8ea6977186323cebfec4d9913e62d75bdcef19621494889412c96598313f77f41fd2cf0ff0355f2fab2e71a4af6ead3a4f35b07edbaa64a3bb96a442b9d2",
          "sha256": "ccb7fde58ecf67a8079ac2eaed28b683584631400c60ae54f767802066569883",
          "sha1": "b6f894196101cb8b63d3be7910268ac94361e59b",
          "md5": "120a540ac7532e7944f34d76b8292644"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cloudscript-module-gradle-plugin-0.4.6.jar",
          "url": "cloudscript-module-gradle-plugin-0.4.6.jar",
          "size": 712844,
          "sha512": "766f8ea6977186323cebfec4d9913e62d75bdcef19621494889412c96598313f77f41fd2cf0ff0355f2fab2e71a4af6ead3a4f35b07edbaa64a3bb96a442b9d2",
          "sha256": "ccb7fde58ecf67a8079ac2eaed28b683584631400c60ae54f767802066569883",
          "sha1": "b6f894196101cb8b63d3be7910268ac94361e59b",
          "md5": "120a540ac7532e7944f34d76b8292644"
        }
      ]
    }
  ]
}
