{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.cloudmc",
    "module": "cloudscript-module-gradle-plugin",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cloudscript-module-gradle-plugin-0.4.0.jar",
          "url": "cloudscript-module-gradle-plugin-0.4.0.jar",
          "size": 687505,
          "sha512": "f64adb29699f1b4733419ef2ce525123083d70749a38fc28f273642637f21d6c17b49cbcf8392c6a0b58450247c286a8dce4c99358ac2eeee78dbecc60eaeae6",
          "sha256": "dd4776b04a5e40030801c002b45c7a15434103eb509484f5c2ed69ccca660a6f",
          "sha1": "c9b7786587b6ee37752e3a60cd223975ac20e2d5",
          "md5": "ca8966d240a729b620684c53c80946c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cloudscript-module-gradle-plugin-0.4.0.jar",
          "url": "cloudscript-module-gradle-plugin-0.4.0.jar",
          "size": 687505,
          "sha512": "f64adb29699f1b4733419ef2ce525123083d70749a38fc28f273642637f21d6c17b49cbcf8392c6a0b58450247c286a8dce4c99358ac2eeee78dbecc60eaeae6",
          "sha256": "dd4776b04a5e40030801c002b45c7a15434103eb509484f5c2ed69ccca660a6f",
          "sha1": "c9b7786587b6ee37752e3a60cd223975ac20e2d5",
          "md5": "ca8966d240a729b620684c53c80946c0"
        }
      ]
    }
  ]
}
