{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.cloudmc",
    "module": "cloudscript-module-gradle-plugin",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cloudscript-module-gradle-plugin-0.4.2.jar",
          "url": "cloudscript-module-gradle-plugin-0.4.2.jar",
          "size": 687551,
          "sha512": "611999ed53af23a3697ae3f326f061f96b5290b30bd4c63e3dfd8507abeca416135d1516564444dbd234be9713075e45466747b3a496c594345507ff92fdb337",
          "sha256": "7f4dfa4aee16bb15bb873e7bf65ae7e8c75391d8bfdef339b84e888b6bcb184c",
          "sha1": "2fb0f0c0f414a4eada2a0c5cee42ebab7cd46e33",
          "md5": "9cc24b0fa58ee71de4660518098ad9e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cloudscript-module-gradle-plugin-0.4.2.jar",
          "url": "cloudscript-module-gradle-plugin-0.4.2.jar",
          "size": 687551,
          "sha512": "611999ed53af23a3697ae3f326f061f96b5290b30bd4c63e3dfd8507abeca416135d1516564444dbd234be9713075e45466747b3a496c594345507ff92fdb337",
          "sha256": "7f4dfa4aee16bb15bb873e7bf65ae7e8c75391d8bfdef339b84e888b6bcb184c",
          "sha1": "2fb0f0c0f414a4eada2a0c5cee42ebab7cd46e33",
          "md5": "9cc24b0fa58ee71de4660518098ad9e2"
        }
      ]
    }
  ]
}
