name: Publish
on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  public-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -PprojectVersion=${{ github.ref_name }}

      - name: Publish plugin to public Maven directory
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publishAllPublicationsToPublicMavenRepository -PprojectVersion=${{ github.ref_name }}

      - name: Deploy public Maven repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/public-maven
          destination_dir: maven
          keep_files: true
